name: tkyoutubedl
version: '1.0'
summary: OfflineIMAP
description: |
  OfflineIMAP is software that downloads your email mailbox(es) as local
  Maildirs. OfflineIMAP will synchronize both sides via IMAP.
confinement: devmode
base: core18

parts:
  tkyoutubedl:
    plugin: python
    python-version: python3
    source: https://github.com/jkelol111/tkyoutubedl.git
    stage-packages:
      - python-six

apps:
  tkyoutubedl:
    command: bin/offlineimap